# https://github.com/dockur/macos
name: "docker-macos"


services:
  macos:
    image: ghcr.io/dockur/macos:1.14
    container_name: macos
    restart: no
    ports:
      - 8006:8006       # Browser Endpoint
      - 5900:5900/tcp   # 
      - 5900:5900/udp   # 
    volumes:
      - ./macos:/storage
      - ./shared:/data
      # - ./example.iso:/custom.iso
      # - ./postinstall:/oem  # "install.bat"
      # - ./disk2:/storage2
      # - ./disk3:/storage3
    environment:
      - VERSION=${VERSION}
      - DISK_SIZE=${DISK_SIZE}
      # - RAM_SIZE=${RAM_SIZE}
      # - CPU_CORES=${CPU_CORES}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m


networks:
  default:
    external: true
    name: proxynet
