# Nextcloud
version: "3.8"
name: "nextcloud"


services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
    volumes:
      - /mnt/data/docker/nextcloud/nextcloud/config:/config
      - /mnt/data/docker/nextcloud/nextcloud/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    volumes:
      - /mnt/data/docker/nextcloud/database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass


networks:
  default:
    external: true
    name: proxynet
