# Nextcloud
# https://chrisgrime.medium.com/deploy-nextcloud-with-docker-compose-935a76a5eb78
name: "nextcloud"


services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
      - redis
    volumes:
      - /mnt/data/docker/nextcloud/nextcloud/html:/var/www/html
      - /mnt/data/docker/nextcloud/nextcloud/custom_apps:/var/www/html/custom_apps
      - /mnt/data/docker/nextcloud/nextcloud/config:/var/www/html/config
      - /mnt/data/docker/nextcloud/nextcloud/data:/var/www/html/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - REDIS_HOST=${REDIS_HOST}
  
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/data/docker/nextcloud/database/data:/var/lib/mysql
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - COLLABORA_USERNAME=${COLLABORA_USERNAME}
      - COLLABORA_PASSWORD=${COLLABORA_PASSWORD}
      - domain=${DOMAIN}
      - extra_params=${EXTRA_PARAMS}
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - /mnt/data/docker/nextcloud/redis/data:/data


networks:
  default:
    external: true
    name: proxynet
