# Nextcloud
# https://chrisgrime.medium.com/deploy-nextcloud-with-docker-compose-935a76a5eb78
version: "3.8"
name: "nextcloud"


services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
      - redis
    ports:
      - 8080:80
    volumes:
      - /mnt/data/docker/nextcloud/nextcloud/html:/var/www/html
      - /mnt/data/docker/nextcloud/nextcloud/custom_apps:/var/www/html/custom_apps
      - /mnt/data/docker/nextcloud/nextcloud/config:/var/www/html/config
      - /mnt/data/docker/nextcloud/nextcloud/data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=redis
  
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/data/docker/nextcloud/database/data:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
  
  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - password=pass
      - username=user
      - domain=nas.j4nis05.ch
      - extra_params=--o:ssl.enable=true
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - /mnt/data/docker/nextcloud/redis/data:/data


networks:
  default:
    external: true
    name: proxynet
