version: "3.8"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail.j4nis05.ch
    domainname: j4nis05.ch
    container_name: mailserver
    restart: always
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    # env_file: mailserver.env
    ports:
      - 25:25
      - 143:143
      - 587:587
      - 993:993
      - 4190:4190
    volumes:
      - /docker/mail/dms/maildata:/var/mail
      - /docker/mail/dms/mailstate:/var/mail-state
      - /docker/mail/dms/maillogs:/var/log/mail
      - /docker/mail/dms/config/:/tmp/docker-mailserver/
      - /docker/mail/dms/cron/sa-learn:/etc/cron.d/sa-learn
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt