version: "3.8"
services:
  liveterm:
    container_name: www.j4nis05.ch
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3000'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev

networks:
  default:
    external: true
    name: proxynet
