# Satisfactory-1 (Wohnzimmer Chill)
name: "satisfactory1"


services:
  satisfactory-1:
    image: wolveix/satisfactory-server
    container_name: satisfactory-chill
    restart: always
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - /docker/games/satisfactory-chill/backups:/config/backups
      - /docker/games/satisfactory-chill/gamefiles:/config/gamefiles
      - /docker/games/satisfactory-chill/logs:/config/logs
      - /docker/games/satisfactory-chill/saved:/config/saved
    environment:
      - MAXPLAYERS=${MAXPLAYERS}
      - PGID=${PGID}
      - PUID=${PUID}
      - ROOTLESS=${ROOTLESS}
      - STEAMBETA=${STEAMBETA}
      - AUTOSAVENUM=${AUTOSAVENUM}
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s


networks:
  default:
    external: true
    name: proxynet
