version: "3.8"

services:
  meshcentral:
    container_name: meshcentral
    restart: unless-stopped
    image: typhonragewind/meshcentral
    environment:
      - HOSTNAME=mesh.j4nis05.ch
      - REVERSE_PROXY=mesh.j4nis05.ch
      - REVERSE_PROXY_TLS_PORT=
      - IFRAME=false
      - ALLOW_NEW_ACCOUNTS=false
      - WEBRTC=false
    volumes:
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files

networks:
  default:
    external: true
    name: proxynet
