# Terraria Server for Nuke
name: "terraria-nuke"


services:
  terraria-nuke:
    image: ghcr.io/beardedio/terraria:latest
    container_name: terraria-nuke
    restart: always
    ports:
      - 8888:7777
    volumes:
      - /docker/games/terraria-nuke:/config
    environment:
      - world=${WORLD}
    tty: true
    stdin_open: true


networks:
  default:
    external: true
    name: proxynet
