# https://github.com/dockur/windows
name: "docker-windows"


services:
  windows:
    image: ghcr.io/dockur/windows:4.00
    container_name: windows
    restart: no
    ports:
      - 8006:8006       # Browser Endpoint
      - 3389:3389/tcp   # Remote Desktop
      - 3389:3389/udp   # Remote Desktop
    volumes:
      - ./windows:/storage
      - ./shared:/data
      # - ./example.iso:/custom.iso
      # - ./postinstall:/oem  # "install.bat"
      # - ./disk2:/storage2
      # - ./disk3:/storage3
    environment:
      - VERSION=${VERSION}
      - DISK_SIZE=${DISK_SIZE}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - LANGUAGE=${LANGUAGE}
      - REGION=${REGION}
      - KEYBOARD=${KEYBOARD}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m


networks:
  default:
    external: true
    name: proxynet
