# https://github.com/dockur/windows
name: "docker-windows"


services:
  windows:
    image: ghcr.io/dockur/windows:4.00
    container_name: windows
    restart: always
    ports:
      - 8006:8006       # Browser Endpoint
      - 3389:3389/tcp   # Remote Desktop
      - 3389:3389/udp   # Remote Desktop
    volumes:
      - ./windows:/storage
      - ./shared:/data
      # - ./example.iso:/custom.iso
      # - ./postinstall:/oem  # "install.bat"
      # - ./disk2:/storage2
      # - ./disk3:/storage3
    environment:
      - VERSION=win11   # Windows 11 Pro
      # - VERSION=ltsc11  # Windows 11 LTSC
      # - VERSION=win11e  # Windows 11 Enterprise
      # - VERSION=win10   # Windows 10 Pro
      # - VERSION=ltsc10  # Windows 10 LTSC
      # - VERSION=win10e  # Windows 10 Enterprise
      # - VERSION=win8    # Windows 8.1 Pro
      # - VERSION=win8e   # Windows 8.1 Enterprise
      # - VERSION=win7    # Windows 7 Enterprise
      # - VERSION=vista   # Windows Vista Enterprise
      # - VERSION=winxp   # Windows XP Professional
      # - VERSION=2025    # Windows Server 2025
      # - VERSION=2022    # Windows Server 2022
      # - VERSION=2019    # Windows Server 2019
      # - VERSION=2016    # Windows Server 2016
      # - VERSION=2012    # Windows Server 2012
      # - VERSION=2008    # Windows Server 2008
      # - VERSION=2003    # Windows Server 2003
      # - VERSION="https://example.com/win.iso"
      - DISK_SIZE=64G
      # - MANUAL=Y
      # - RAM_SIZE=4G
      # - CPU_CORES=2
      - USERNAME=vmadmin
      - PASSWORD=sml12345
      - LANGUAGE=English
      - REGION="de-CH"
      - KEYBOARD="de-CH"
      # - DISK2_SIZE="32G"
      # - DISK3_SIZE="64G"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m


networks:
  default:
    external: true
    name: proxynet
