version: "3.8"

services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archiveTeamWarrior
    hostname: archiveTeamWarrior
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    environment:
      - DOWNLOADER=J4nis05
      - SELECTED_PROJECT=auto
      - CONCURRENT_ITEMS=5

  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./tools/gitea/data:/data
      - ./tools/gitea/config:/etc/gitea

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./tools/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
  
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: always
    volumes:
      - /docker/ext/data/docker/matrix/data:/data
    environment:
      VIRTUAL_HOST: "j4nis05.ch"
      VIRTUAL_PORT: 8008
      SYNAPSE_SERVER_NAME: "j4nis05.ch"
      SYNAPSE_REPORT_STATS: "yes"

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./tools/vaultwarden:/data


networks:
  default:
    external: true
    name: proxynet
