version: "3.8"

services:
  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: always
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    depends_on:
      - nextcloud-db
    volumes:
      - /docker/ext/data/docker/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

networks:
  default:
    external: true
    name: proxynet
