---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Nyx - Homepage

background: 
  image: /app/config/img/background.jpg
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

headerStyle: boxed

cardBlur: sm

theme: dark

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

hideVersion: true

showStats: true
