version: "3.8"

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80     # HTTP Redirect Port
      - 443:443   # HTTPS Redirect Port
      - 81:81     # Management Port
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Zurich
      - DISABLE_IPV6=true

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr_configs:/app/data/configs
      - homarr_icons:/app/public/icons
      - homarr_data:/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: proxynet

volumes:
  nginx_data:
  nginx_letsencrypt:
  homarr_configs:
  homarr_icons:
  homarr_data:
