version: "3.8"

services:
  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    restart: always
    ports:
      - 80:80     # HTTP Redirect Port
      - 443:443   # HTTPS Redirect Port
      - 81:81     # Management Port
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Zurich
      - DISABLE_IPV6=true

  example:
    image: 
    container_name: 
    restart: always
    ports:
      - 
    volumes:
      - 
    environment:
      - 


networks:
  default:
    external: true
    name: proxynet

volumes:
  