version: "3.8"

services:
  example:
    image: 
    container_name: 
    restart: always
    ports:
      - 
    volumes:
      - 
    environment:
      - 

networks:
  default:
    external: true
    name: proxynet

volumes:
  