# Core Services (Nginx Proxy Manager & Watchtower)
version: "3.8"
name: "services"


services:
  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    restart: always
    ports:
      - 80:80     # HTTP Redirect Port
      - 443:443   # HTTPS Redirect Port
      - 81:81     # Management Port
    volumes:
      - /mnt/data/docker/services/nginx/data:/data
      - /mnt/data/docker/services/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Zurich
      - DISABLE_IPV6=true

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  default:
    external: true
    name: proxynet
