version: "3.7"
services:
  liveterm:
    container_name: liveterm
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3000'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev

networks:
  default:
    external: true
    name: proxynet
