version: "3.8"

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    restart: always
    depends_on:
      - synapse_db
    volumes:
      - synapse_data:/data
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml

  synapse_db:
    image: docker.io/postgres:12-alpine
    container_name: synapse_db
    restart: always
    volumes:
      - synapse_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C

networks:
  default:
    external: true
    name: proxynet

volumes:
  synapse_data:
  synapse_db_data:
