version: '3'

services:
  minecraft-server:
    image: j4nis05/minecraft-server:latest
    container_name: mc-atm9
    restart: always
    command: bash -c /minecraft/startserver.sh
    ports:
      - "25566:25565"
      - "25576:25575"
    volumes:
      - /docker/atm9:/minecraft