# Portainer
name: "portainer"


services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000   # HTTP Port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/docker/portainer/portainer/data:/data


networks:
  default:
    external: true
    name: proxynet
