# Portainer
version: "3.8"
name: "portainer"


services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000   # HTTP Port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


networks:
  default:
    external: true
    name: proxynet


volumes:
  portainer_data:
