version: "3.8"

services:
    jellyfin:
      container_name: jellyfin
      image: jellyfin/jellyfin:latest
      restart: always
      volumes:
        - ./jellyfin/config:/config
        - ./jellyfin/cache:/cache
        - /nas:/media

networks:
  default:
    external: true
    name: proxynet
