# Satisfactory-3 (Extra Server)
name: "satisfactory3"


services:
  satisfactory-1:
    image: wolveix/satisfactory-server
    container_name: satisfactory-3
    restart: always
    ports:
      - '7779:7777/udp'
      - '7779:7777/tcp'
    volumes:
      - /docker/games/satisfactory-3/backup:/config/backups
      - /docker/games/satisfactory-3/gamefiles:/config/gamefiles
      - /docker/games/satisfactory-3/logs:/config/logs
      - /docker/games/satisfactory-3/saved:/config/saved
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - AUTOSAVENUM=15
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s


networks:
  default:
    external: true
    name: proxynet
