name: "archive-scraperr"

services:
  scraperr_frontend:
    image: jpyles0524/scraperr:latest
    container_name: scraperr_frontend
    restart: always
    expose:
      - 3000

  scraperr_api:
    image: jpyles0524/scraperr_api:latest
    container_name: scraperr_api
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=INFO
      #- OLLAMA_URL=http://ollama:11434
      #- OLLAMA_MODEL=phi3
      # or
      # - OPENAI_KEY=<your_key>
      # - OPENAI_MODEL=gpt3.5-turbo
      - MONGODB_URI=mongodb://root:pass@scraperr_db:27017
      - SECRET_KEY=4af1e5737b55dfa1e4f37c3a484b5d25d17d514fbc8553d78554dcd2c8a237fc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=600
    init: true
    expose:
      - 8000

  scraperr_db:
    image: mongo:latest
    container_name: scraperr_db
    restart: always
    volumes:
      - /docker/data/archive/scraperr-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass


networks:
  default:
    external: true
    name: proxynet
