version: "3.8"

services:
  pingvin:
    image: stonith404/pingvin-share
    container_name: pingvin
    restart: unless-stopped
    volumes:
      - /docker/ext/data/docker/pingvin/data:/opt/app/backend/data
      - /docker/ext/data/docker/pingvin/data/images:/opt/app/frontend/public/img

  smb-web:
    image: filebrowser/filebrowser
    container_name: smb-web
    restart: unless-stopped
    volumes:
      - /docker/ext/data:/srv/smb
      - /docker/ext/smb:/srv/qbit
      - /docker/ext/qbit:/srv/data

networks:
  default:
    external: true
    name: proxynet