# Synapse Server
# https://linuxhandbook.com/install-matrix-synapse-docker/#step-2-set-up-synapse
# homeserver.yaml generation: docker compose run --rm matrix generate
# Element Sample Config: https://develop.element.io/config.json
# https://cyberhost.uk/element-matrix-setup/
version: "3.8"
name: "matrix"


services:
  element:
    image: vectorim/element-web
    container_name: element
    restart: always
    volumes:
      - /mnt/data/docker/matrix/element/config.json:/app/config.json

  matrix:
    image: matrixdotorg/synapse
    container_name: matrix
    restart: always
    depends_on:
      - matrix-db
    volumes:
      - /mnt/data/docker/matrix/matrix/data:/data
    environment:
      - VIRTUAL_HOST=matrix.j4nis05.ch
      - VIRTUAL_PORT=8008
      - LETSENCRYPT_HOST=matrix.j4nis05.ch
      - SYNAPSE_SERVER_NAME=matrix.j4nis05.ch
      - SYNAPSE_REPORT_STATS=no
  
  matrix-db:
    image: postgres
    container_name: matrix-db
    restart: always
    volumes:
      - /mnt/data/docker/matrix/matrix-db/data:/var/lib/postgresql/
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS="--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"


networks:
  default:
    external: true
    name: proxynet
