# Synapse Server
# https://linuxhandbook.com/install-matrix-synapse-docker/#step-2-set-up-synapse
# homeserver.yaml generation: docker compose run --rm matrix generate
# Element Sample Config: https://develop.element.io/config.json
# https://cyberhost.uk/element-matrix-setup/
name: "matrix"


services:
  element:
    image: vectorim/element-web
    container_name: element
    restart: always
    volumes:
      - /mnt/data/docker/matrix/element/config.json:/app/config.json

  matrix:
    image: matrixdotorg/synapse
    container_name: matrix
    restart: always
    depends_on:
      - matrix-db
    volumes:
      - /mnt/data/docker/matrix/matrix/data:/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
      - SYNAPSE_REPORT_STATS=${SYNAPSE_REPORT_STATS}
  
  matrix-db:
    image: postgres
    container_name: matrix-db
    restart: always
    volumes:
      - /mnt/data/docker/matrix/matrix-db/data:/var/lib/postgresql/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}


networks:
  default:
    external: true
    name: proxynet
