# Arr (Jellyfin & co.)
name: "arr"


services:
  qbittorrent:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrent
    restart: always
    ports:
      - 6881:6881       # Port Required for BitTorrent
      - 6881:6881/udp   # Port Required for BitTorrent
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/qbit:/data
      - /mnt/data/docker/arr/qbittorrent/config:/config
      - /mnt/data/docker/arr/qbittorrent/theme:/theme
    environment:
      - VPN_ENABLED=${VPN_ENABLED}
      - VPN_PROV=${VPN_PROV}
      - VPN_CLIENT=${VPN_CLIENT}
      - STRICT_PORT_FORWARD=${STRICT_PORT_FORWARD}
      - ENABLE_PRIVOXY=${ENABLE_PRIVOXY}
      - WEBUI_PORT=${WEBUI_PORT}
      - LAN_NETWORK=${LAN_NETWORK}
      - PUID=${PUID}
      - GUID=${GUID}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    volumes:
      - /nas:/media
      - /mnt/data/docker/arr/jellyfin/config:/config
      - /mnt/data/docker/arr/jellyfin/cache:/cache

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: always
    volumes:
      - /mnt/data/docker/arr/jellyseerr/config:/app/config
    environment:
      - TZ=${TZ}
      - PORT=${JELLYSEERR_PORT}
      - LOG_LEVEL=${JELLYSEERR_LOG_LEVEL}

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: always
    volumes:
      - /mnt/data/docker/arr/sonarr/config:/config
      - /mnt/qbit:/data
      - /nas:/nas
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: always
    volumes:
      - /mnt/data/docker/arr/radarr/config:/config
      - /mnt/qbit:/data
      - /nas:/nas
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: always
    volumes:
      - /mnt/data/docker/arr/prowlarr/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    restart: always
    volumes:
      - /mnt/data/docker/arr/podgrab/config:/config
      - /nas/media/audio/podcasts:/assets
    environment:
      - CHECK_FREQUENCY=${CHECK_FREQUENCY}


networks:
  default:
    external: true
    name: proxynet
