# Satisfactory-2 (Wohnzimmer Sweat)
name: "satisfactory2"


services:
  satisfactory-1:
    image: wolveix/satisfactory-server
    container_name: satisfactory-sweat
    restart: always
    ports:
      - '7778:7777/udp'
      - '7778:7777/tcp'
    volumes:
      - /docker/games/satisfactory-sweat/backup:/config/backups
      - /docker/games/satisfactory-sweat/gamefiles:/config/gamefiles
      - /docker/games/satisfactory-sweat/logs:/config/logs
      - /docker/games/satisfactory-sweat/saved:/config/saved
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - AUTOSAVENUM=15
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s


networks:
  default:
    external: true
    name: proxynet
