# Satisfactory-2 (Wohnzimmer)
version: "3.8"
name: "satisfactory2"


services:
  satisfacotry-2:
    image: wolveix/satisfactory-server
    container_name: satisfactory-2
    restart: always
    ports:
      - 7777:7777/udp   # Game Port
      - 15000:15000/udp # Beacon Port
      - 15777:15777/udp # Query Port
    volumes:
      - /mnt/data/docker/games/satisfactory2/config:/config
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 14G


networks:
  default:
    external: true
    name: proxynet
