version: "3.8"

services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
     - CHECK_FREQUENCY=240
    volumes:
      - ./podgrab/:/config
      - /nas/media/audio/podcasts:/assets
    restart: always

networks:
  default:
    external: true
    name: proxynet
