version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default:
    external: true
    name: proxynet
