# Minecraft Vanilla Server
name: "mc-vanilla"


services:
  mc-wohnzimmer:
    image: eclipse-temurin:22-jre-alpine
    container_name: mc-wohnzimmer
    restart: always
    command: java -Xmx8192M -Xms8192M -jar /minecraft/server.jar nogui
    ports:
      - 25565:25565   # Port for Server Access
      - 25575:25575   # Port for Remote Console Access
    volumes:
      - /docker/games/vanilla:/minecraft
    working_dir: /minecraft


networks:
  default:
    external: true
    name: proxynet
