# Minecraft Vanilla Server
version: "3.8"
name: "mc-vanilla"


services:
  mc-wohnzimmer:
    image: j4nis05/minecraft-server:latest
    container_name: mc-wohnzimmer
    restart: always
    command: java -Xmx4096M -Xms4096M -jar /minecraft/server.jar nogui
    ports:
      - 25565:41340   # Port for Server Access
      - 25575:25575   # Port for Remote Console Access
    volumes:
      - /mnt/data/docker/gameserver/vanilla:/minecraft


networks:
  default:
    external: true
    name: proxynet


volumes:
  