name: ""


services:
  example:
    image: 
    container_name: 
    restart: always
    depends_on:
      - 
    ports:
      - 
    volumes:
      - 
    environment:
      - 
    # Any Additional Instructions at the End
    # Single newline between services


networks:
  default:
    external: true
    name: proxynet